# Generated by Django 4.2.10 on 2024-05-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobapp', '0002_propriedade_codigo_alter_propriedade_finalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='foto1',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
