# Generated by Django 4.2.10 on 2024-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobapp', '0003_alter_propriedade_foto1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='foto1',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto10',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto5',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto7',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto8',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='foto9',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
