# Generated by Django 4.2.10 on 2024-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobapp', '0004_alter_propriedade_foto1_alter_propriedade_foto10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='video',
            field=models.URLField(blank=True),
        ),
    ]
